services:
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: compiler-observer:latest
    container_name: compiler-observability-test-build
    command: ["sh", "-c", "tasks/async-task-execution/run-tests.sh"]
    volumes:
      - ../../:/app/project
    working_dir: /app/project
