services:
  app:
    build: .
    image: projectz-base-runner:latest
    command: [ "./run_tests.sh", "${TASK_ID:-BASE}" ]
    environment:
      - TASK_ID=${TASK_ID:-BASE}
    volumes:
      - .:/app
      - ..:/workspace
