services:
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: projectz-metric-time-filtering:latest
    container_name: compiler-observability-test-build
    command: ["sh", "-c", "tasks/metric-time-filtering/run-tests.sh"]
    volumes:
      - ../../:/app/project
    working_dir: /app/project
