services:
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: projectz-aggregation-period-keys:latest
    container_name: compiler-observability-test-build
    command: ["sh", "-c", "tasks/aggregation-period-keys/run-tests.sh"]
    volumes:
      - ../../:/app/project
    working_dir: /app/project
