services:
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: projectz-event-collection-validation:latest
    container_name: compiler-observability-test-build
    command: ["sh", "-c", "tasks/event-collection-validation/run-tests.sh"]
    volumes:
      - ../../:/app/project
    working_dir: /app/project
