services:
  client:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: projectz-transaction-atomicity:latest
    container_name: compiler-observability-test-build
    command: ["sh", "-c", "tasks/transaction-atomicity/run-tests.sh"]
    volumes:
      - ../../:/app/project
    working_dir: /app/project
